### ISSUE TITLE
[Feature request] Keyboard shortcut to copy current line result to clipboard

### ISSUE THREAD

**Issue by snippins** [parnold-x/nasc#100]
Thanks so much for developing nasc, it really is the best calculator app I have ever use. 

However, it seems that currently there is no way to copy the result to clipboard than dragging to select and then use Ctrl+c or context menu. 

I usually fire up a nasc (with a shortcut) to quickly calculate something, get the result, go back to the last window with a keyboard shortcut and paste it. Thus, it can get a little frustrating to keep switching between the mouse and keyboard so I find myself prefer to type the results instead. 

Therefore, IMHO, it would be great if we can have a keyboard shortcut to copy the current line's result.

**Comment by parnold-x** [comment]
Works now.
When Ctrl+Shift+C is used and nothing is selected in the InputView. The result is copied to clipbord
