### ISSUE TITLE
Can't save Matrix to Variable

### ISSUE THREAD

**Issue by Hedronmx** [parnold-x/nasc#102]
I can't save matrix to variables, so i can't do any calculations with matrices
![image](https://user-images.githubusercontent.com/26935602/50850046-a4273600-132d-11e9-9099-e67660fc29a7.png)

**Comment by parnold-x** [comment]
The syntax to define a matrix is **matrix(parameters...)**
Also a = 5 is just a convenience thing. It does not work in all cases to enfore a definition use a := expr
