### ISSUE TITLE
Line wraping

### ISSUE THREAD

**Issue by nick87720z** [parnold-x/nasc#115]
Too long expressions force NaSC window to very big width. Possible example case:
`((0.299 · (1 − ((1 − n) · x))) + (0.587 · (1 − ((1 − y) · x))) + 0.114) = 0.587 + 0.299 and (1 − ((1 − n) · x)) != 0 and (1 − ((1 − y) · x)) != 0`
(some example of multiple equations system)
With resolution
`(0 * factorial(xy − x + 1)) && x = 114 ∕ (886 − 299n − 587y) && factorial(nx − x + 1) = 0 && y ≠ 1.5093697 − 0.50936968n`

As for result pane - it could be both wrapped or just made scrollable. Or may be both to be scrollable independently. Current way is that entire area, encompassing both halves is one scrollable area. GtkPanned (or what is it) handle in the middle doesn't make sence in such situation.

Edit: I initially did all this in reference qalculate-gtk, but decided to try nasc again when found, that it can save log (useful thing for reports, student works, etc).

**Comment by parnold-x** [comment]
fixed
