### ISSUE TITLE
Number conversion feature is not working.

### ISSUE THREAD

**Issue by yezhidal** [parnold-x/nasc#116]
This feature is required for dealing with a memory address arithmetic or with some low-level C/ASM code, but it is not working (or not implemented). For example, when I write this expression in NaSC (12300 to hex) I will get this number in the answer (12300).
I know about "Qalculate!" app, but it will be much handier to do such calculations in NaSC.
![Screenshot from 2019-03-25 15-23-41](https://user-images.githubusercontent.com/40965417/54919579-3513b380-4f12-11e9-8b69-7aa746fca9c5.png)

**Comment by YeZhidal** [comment]
Looking through closed issues, I found one, that is connected with this problem. It is issue #59. You wrote about adding this feature https://github.com/parnold-x/nasc/issues/59#issuecomment-321259713.

**Comment by Hedronmx** [comment]
Please add this :( I need it.

**Comment by parnold-x** [comment]
This works now. Available are to:
`hex
bin
dec
oct
duo
roman
bijective
roman
sexa
fp32
fp64
fp16
fp80
fp128`
