### ISSUE TITLE
Double NaSC icon in Plank

### ISSUE THREAD

**Issue by dvanderfaeillie** [parnold-x/nasc#117]
A while ago I updated NaSC on my elementary OS Juno setup.

Since then when I open the NaSC app a second icon with the proper app appears... 
Any ideas on how to resolve this issue?
![Schermafdruk van 2019-03-27 19 06 26](https://user-images.githubusercontent.com/1950967/55101332-2a008500-50c4-11e9-9928-6f0450111681.png)

**Comment by dcharles525** [comment]
I fixed this here: https://github.com/parnold-x/nasc/pull/119 if you want to try it out @dvanderfaeillie

**Comment by dvanderfaeillie** [comment]
I've applied the changes in `com.github.parnold-x.nasc.desktop` and indeed, that seems to fix it.
Thanks @dcharles525
