### ISSUE TITLE
Missing graphic elements in compose window

### ISSUE THREAD

**Issue by CaseOf** [parnold-x/nasc#121]
Hello,
I wrote an ebuild to install NaSC on my Gentoo system and try it.
I can see some graphic are missing. I do not know if it is caused by a missing theme or font.
In the example attached, `ans` is missing but appears in exported PDF document.
![screenshot here](https://pix.toile-libre.org/upload/original/1557706209.png)
[PDF document exported](https://framadrop.org/r/SfrAV_wtiU#n1R+IViJcb+SlsbfRpNLsWiFCFUbHr/d4L9nft865MY=)
[(mirror)](https://www.scribd.com/document/409701842/Sheet)

**Comment by d5ve** [comment]
I also get this on Ubuntu Disco when compiling from source with 3452e9df2a

**Comment by parnold-x** [comment]
I can't reproduce this on the elementary theme. So maybe it is a theme issue? Anyway I need more info to reproduce this.
