### ISSUE TITLE
Use libqualculate as git submodule

### ISSUE THREAD

**Issue by parnold-x** [parnold-x/nasc#130]
Given the fact that the  distro libqualculate in elementary is somehow old and upstream  (❤️ ) is quite active it would be better if this is a git submodule, build at buildtime and then linked statically or so.

**Comment by scx** [comment]
What version of `libqualculate` is currently recommended?
What version do you use in the snap package?
If I good remember, `nasc` was a little bit unstable with `libqualculate` _0.9.x_. However, I am not sure if it is compatible with the latest version. So, which version does it work best with?

**Comment by scx** [comment]
One more thing: `libqualculate` requires `mpfr` and `cln`. Should we bundle them as well?

**Comment by parnold-x** [comment]
I did not make any snap package. So don't know what is packaged there. I tested it with the ubuntu 18.04 bundled version which is 0.9.10-1
It should work with the newest version. I am not using much of libqalculate. See https://github.com/parnold-x/nasc/blob/master/libqalculatenasc/QalculateNasc.cc#L246
If changes are needed for the newest version I am happy to make them. 
For the other dependencies. I don't know if this is necessary. libcln e.g. is just needed at build time. Right?

**Comment by scx** [comment]
> It should work with the newest version. I am not using much of libqalculate

I observed a strange behavior when using `libqalculate` >= _3.x.x_.

`libqalculate-3.5.0a`:

![NaSC-libqalculate-3 5 0a](https://user-images.githubusercontent.com/510369/67766975-003f8000-fa50-11e9-9771-d697224645a4.png)

It doesn't occur with `libqalculate` _2.x.x_.

`libqalculate-2.9.0`:

![NaSC-libqalculate-2 9 0](https://user-images.githubusercontent.com/510369/67767130-4563b200-fa50-11e9-9fd3-3e924c20b1a1.png)

What do you think about this?

**Comment by parnold-x** [comment]
Mhh, ok. I guess it is this https://github.com/Qalculate/libqalculate/releases/tag/v3.0.0
> Separate use of interval arithmetic, to keep track of precision changes with approximate calculations, from selection of interval calculation algorithm (by default both interval arithmetic and uncertainty propagation using variance formula are now activated).

> https://github.com/Qalculate/libqalculate/blob/master/libqalculate/Calculator.h#L1150

I played around a lot with the settings at the beginning to find good defaults. Maybe it helps to deactivate this new interval arithmetic
add 

> calc->useIntervalArithmetic(false);

here https://github.com/parnold-x/nasc/blob/master/libqalculatenasc/QalculateNasc.cc#L254

**Comment by parnold-x** [comment]
Ok, so I thought it would be easier with meson but I can't get it to work. 
I can call a custom command to let autotools build libqalculate and it spits out
.so and .a files. Then I want to link ths output in meson but i can't get it to work with custom_target or link_with or compiler flags.

**Comment by parnold-x** [comment]
With this meson it builds https://gist.github.com/parnold-x/b757cedf78b6323e568658e1aad1ae00

But then fails at the linking step https://gist.github.com/parnold-x/eda85a08787e5840e5424b520b9fb119
