### ISSUE TITLE
NaSC on macOS

### ISSUE THREAD

**Issue by adamonsoon** [parnold-x/nasc#131]
Hey, I really love NaSC and feel its absence when using a mac. I used MacPorts to get `qalc` and `qalculate-gtk` running, but that's really not as nice. I was wondering how complex would it be to port NaSC to macOS. Porting is out of my comfort zone, but I'd be happy to give it a try and submit a PR, I just need some high-level guidelines to help focus the effort.

**Comment by parnold-x** [comment]
Hi, I have no experience with that so no clue how to do that.
