### ISSUE TITLE
[FEATURE REQUEST] Save/load/parse markdown documents

### ISSUE THREAD

**Issue by wakatara** [parnold-x/nasc#139]
I'm a heavy user of Calca on OSX which is a symbolic math calculator doing something similar to NaSc here (and which are much like Soulver and Numi on osx.). 

I heart Calca because effectively it's a markdown document that parses results inline (usually via a "=>" indicator) and is very handy not just for figuring things out but saving them over time. 

Is it possible to add similar functionality into NaSC? I was almost at the point of trying to work up an emacs mode to do the same as I move over(back) to Linux but was wondering about your road map for similar functionality. 

thanks!
Daryl

**Comment by parnold-x** [comment]
Hi, looked at the Calca thing and this is not the direction NaSC is going to. The basic concept will stay like it is now with the answers on the right.
I hope to find time this winter to fix some stuff and implement new features.
