### ISSUE TITLE
Struggling to install on Ubuntu 19.10

### ISSUE THREAD

**Issue by harryiliffe** [parnold-x/nasc#140]
Good morning, 
I would love to be able to install this on Ubuntu 19.10, however there is not a release for eoan on the ppa.
I attempted to build the app myself but struggled to gather all the correct dependencies (namely libqalculate and granite). 

What am I missing?

**Comment by parnold-x** [comment]
Tried to build for newer ubuntu version on the ppa but it somehow fails ...
To build you need these https://github.com/parnold-x/nasc/blob/master/debian/control
libqalculate should be in the ubuntu repos. 
granite in elementary daily https://launchpad.net/~elementary-os/+archive/ubuntu/daily/+index?batch=75&memo=75&start=75

**Comment by harryiliffe** [comment]
I have created a pull request to clarify the dependencies listed in the ReadMe. 
After following the link you sent me I was able to build easily. 
To prevent others from wasting time hunting through the repo for the correct dependencies names, they should be in the readme.
Thanks for your help, this app is awesome!
