### ISSUE TITLE
Segfault on copy/cut/paste

### ISSUE THREAD

**Issue by alexdrean** [parnold-x/nasc#144]
Copy/cut/pasting around seems to create glitches (calculations don't run anymore) and segfault. I can reproduce this on every system I can get my hands on.

To reproduce:
Type in a few lines. Copy and paste, delete everything, paste again a few times... Very quickly glitches happen and segfault happen.

Segv analysis seems to point at some strcmp accessing 0x0...090 which is not readable. Seems like a pointer glitch (I know, that's not very useful).

**Comment by alexdrean** [comment]
Investigating a little further, it seems like this is only triggered by CUT/Paste

GDB output
```
Thread 1 "nasc" received signal SIGSEGV, Segmentation fault.
__strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:101
101	../sysdeps/x86_64/multiarch/strcmp-avx2.S: No such file or directory.
```

**Comment by parnold-x** [comment]
Could be fixed but not entirly sure.

**Comment by parnold-x** [comment]
Did some testing with C&P and this seems to be fixed. If not plz reopen.
