### ISSUE TITLE
Add buttons/list down the right side

### ISSUE THREAD

**Issue by rwoolf** [parnold-x/nasc#146]
This is a pretty cool calculator.  But for people like me, who are not in it daily, it would be really helpful if you created a third column on the page that is a list of the commands you can enter, and when you click on one, it adds it to your equation.  If the list on the right were the full descriptive name, and when you click on it on the right it adds it using the abbreviation into your equation just as if it had been typed. 

For example:
Cube Root
Exponential (e^x)
Natural Logarithm
Nth root
...

This is basically what you have in your help, but these would always remain on the screen and are buttons that behave much like when you click on an answer.  When you click on Exponential (e^x) it would add exp() into your equation.  For people like me who aren't in the app enough to memorize everything, this is a very shortcut way to be more productive in the app.

**Comment by parnold-x** [comment]
As you say this function is already in the help. So I don't see the need to replicated that.
Ctrl-H to open the Help -> type **exp** to go to the category and double click on the function to add it in. Ctrl-H to close it.
