### ISSUE TITLE
"= " in comments can cause buggy behaviour

### ISSUE THREAD

**Issue by cougarten** [parnold-x/nasc#157]
**Describe the bug**
`myVar = 1337 // this means me = super haXXor`should still assign 1337 to myVar. The `= `however causes it to assign 1 or 0

**To Reproduce**
1. paste `myVar = 1337 // this means me = super haXXor`
2. observe result on the right
3. move your cursor to the beginning of the line
4. hit return a few times for new lines

**Expected behavior**
- Result on the right should show 1337 all the time. (not 0 or 1)
- empty lines should show no result
- it should not remove characters (look at the end of the line when hitting return a few times. It adds an "r" and removes text)

**Screenshots**
![image](https://user-images.githubusercontent.com/7131556/89311175-f2b9c500-d675-11ea-96f3-ac961199c873.png)

**Desktop (please complete the following information):**
 - OS: Xubuntu
- No idea how to find the nasc version, but I think I recently built from source.

BTW:
- comments should make it in to the documentation I think :)
- thank you for nasc! Just moved to linux and would have missed the other tools badly!

**Comment by parnold-x** [comment]
I fixed the comment bug. It should also handle whitespace with variables better. 
Also the update of the result while line movements should be handled now better.
