### ISSUE TITLE
Feature Request - Custom functions

### ISSUE THREAD

**Issue by darrSonik** [parnold-x/nasc#158]
I don't if this feature is available or not. If available, can anyone point me to the Wiki/Help. I can't find any.
If it's not available, can you implement it please? It's helpful if I can define temporary functions for doing some math.

For example:
to calculate kinetic energy it would be helpful to have a function like

`kineticEnergy(mass, speed) = 0.5 * mass * speed^2`

and assign it like `car = kineticEnergy(1000 kg, 3 m/s)`

or assign it like `car = kineticEnergy(1000, 3)` <- if it's like this, we have to calculate the units ourselves, but that's acceptable.

**Comment by parnold-x** [comment]
Hi, this should be possible but I have no time to test it right now. To define a function see https://github.com/Qalculate/qalculate-gtk/issues/90
I am not sure how to call it then though.  If you figure it out please post it here.

**Comment by parnold-x** [comment]
This works now. So for your example
`function kineticEnergy 0.5 * \x* \y ^2`
You the can assign it like you wanted. Units also works

The variables must be \x, \y, \z, \a,...
