### ISSUE TITLE
Change theme

### ISSUE THREAD

**Issue by Adelta-py** [parnold-x/nasc#161]
Hi, i would like to change the colors of the software, because half of my screen is blue on black, the other is white on light grey
I searched for an option and couldn't find it
Does it exist ?
And if not, can I still change the colors ?

**Comment by parnold-x** [comment]
Right now in lack of a better setting it listen to the prefer dark setting.

-----
Step 1: Open the GTK3 configuration file in Text Editor:

gedit ~/.config/gtk-3.0/settings.ini

Step 2: Paste this into the file opened by Text Editor:

[Settings]
gtk-application-prefer-dark-theme=1

**Comment by Adelta-py** [comment]
Thank you!
