### ISSUE TITLE
Unnecessary spaces after operators when deleted

### ISSUE THREAD

**Issue by KomradBear** [parnold-x/nasc#166]
**Describe the bug**
Every time you type a number or an operator you get automatic spaces between elements, but after deleting an operator and adding a new one and then deleting it again you get extra spaces pushing the cursor further and further away.

And so, when doing large amount of numbers and operators you always get extra spaces here and there when fixing or adjusting formulas or mistakes. This creates a visually unpleasing document with holes between elements

**To Reproduce**
Type test = 10
then delete the equals sign, and type it again, and repast over and over again and see the "10" being pushed away with the cursor.

**Expected behavior**
There should be no extra spaces after deleting a symbol or a number or any sort of element.

**Video**
https://user-images.githubusercontent.com/68272253/117782271-226fac00-b24a-11eb-8de4-ebe74553429f.mp4

**Desktop**
 - elementary OS 5.1.7
 - NaSC Version 0.7.5

**Suggestion**
Automatic spacing should probably be disabled altogether, instead a special kind of font where only operators have bigger kerning while everything else is at default could be used.

**Comment by parnold-x** [comment]
Hi, thanks.
I like your idea. The spacing is in fact kind of tricky. Do you know such a font?

**Comment by KomradBear** [comment]
Unfortunately none that I'm aware of... If such font wont be found or made, maybe another solution for "beautifying" the formulas is automatically rendering a LaTeX output?

For example if you were to type 1+1 and hit enter to go down a row the 1+1 would get rendered into LaTeX form in real-time right in the editor, then if you press backspace to delete a character it would transfer back into simple editable text. It's almost as having a real-time render for Markdown... just for LaTeX

This is just a wild idea... its going a bit far but its main purpose is to have some sort of "beautifying" system.
Its not necessary, it could be added as a feature that can be turned off in settings if the user doesn't want it. (Render as LaTex > On/Off)

**Comment by parnold-x** [comment]
Ok, thanks for looking. Mhh, I prefer better looking sheets, without spaces it looks kind of ugly and also it is imo less readable. When I find time I fix the issue for now.

**Comment by KomradBear** [comment]
I agree that without spaces it looks somewhat ugly, but it also looks quite ugly with inconsistent spaces which I find my self constantly fixing.

I think letting the user decide if he wants automatic spaces or not would be a long term solution because honestly at first when I used the app for the first time I manually out of habit hit space on my own... it took me some getting used to the automatic spaces.

Either way, thanks for the app, its very useful.

**Comment by parnold-x** [comment]
Make it optional is even more work. When you do the spaces yourself it shouldn't get in your way, so I don't see the point. Like I said, when I find time I fix the issue.
