### ISSUE TITLE
Make available on ubuntu (or any other distros)

### ISSUE THREAD

**Issue by FlyinPancake** [parnold-x/nasc#167]
Hi I'm a fan of this app on elementary, but I would like to use it on other ubuntu based distros.
Could you provide a deb file or possibly snap or flatpak package so others get to use this wonderful program? Thanks :)

**Comment by parnold-x** [comment]
Hi, thank you. Most likely not, I don't like packaging.
I think elementary plans to move to flatpak at some point in the future for appstore apps. But I don't know when.

**Comment by FlyinPancake** [comment]
Yes, I read about the flatpak move.
I just assumed (as elementary is currently deb based) that you would have some debs available, but if this isn't the case I don't want to trouble you.

ps.: [here](https://blog.elementary.io/appcenter-dashboard-sprint/) seems like devs have to package apps for the new flatpak based appcenter-dashboard

**Comment by parnold-x** [comment]
There are debs. They get build by the elementary CI and pushed to the appstore. I should be able to access them but I don`t know how.
You can also build them from the source and I would merge some Github CI PR to build them automatically.
