### ISSUE TITLE
Theme issue on fedora with white-sur

### ISSUE THREAD

**Issue by aniketfuryrocks** [parnold-x/nasc#176]
![Screenshot from 2021-08-17 17-56-36](https://user-images.githubusercontent.com/42654595/129725465-f2196ec7-605c-4924-9892-c8e2f78150af.png)

**Gtk theme**
[White Sure Theme](https://github.com/vinceliuice/WhiteSur-gtk-theme)

**Issue**
The right pane is not readable
Does not seem to be an issue with the theme.

**Platform**

```bash
❯ neofetch            
          /:-------------:\          aniket@fedora
       :-------------------::        -------------
     :-----------/shhOHbmp---:\      OS: Fedora 34 (Workstation Edition) x86_64
   /-----------omMMMNNNMMD  ---:     Host: 81BF Ideapad 520-15IKB
  :-----------sMMMMNMNMP.    ---:    Kernel: 5.13.9-200.fc34.x86_64
 :-----------:MMMdP-------    ---\   Uptime: 6 hours, 55 mins
,------------:MMMd--------    ---:   Packages: 2381 (rpm), 14 (flatpak)
:------------:MMMd-------    .---:   Shell: fish 3.3.1
:----    oNMMMMMMMMMNho     .----:   Resolution: 1600x900, 1920x1080
:--     .+shhhMMMmhhy++   .------/   DE: GNOME 40.3
:-    -------:MMMd--------------:    WM: Mutter
:-   --------/MMMd-------------;     WM Theme: WhiteSur-dark
:-    ------/hMMMy------------:      Theme: WhiteSur-dark [GTK2/3]
:-- :dMNdhhdNMMNo------------;       Icons: WhiteSur-dark [GTK2/3]
:---:sdNMMMMNds:------------:        Terminal: alacritty
:------:://:-------------::          Terminal Font: black: '0x212121'
:---------------------://            CPU: Intel i5-8250U (8) @ 3.400GHz
                                     GPU: Intel UHD Graphics 620
                                     GPU: NVIDIA GeForce MX150
                                     Memory: 4847MiB / 7721MiB
```

**Comment by parnold-x** [comment]
Hi, this app is optimized for the elementary theme/os. So your problem is that the theme makes the app dark without the app knowing it. 
You must assure that the dark_mode boolean is true https://github.com/parnold-x/nasc/blob/master/src/NascSettings.vala#L56
I am open for PRs to handle this on other os if it`s not breaking things.

**Comment by parnold-x** [comment]
Yeah, I am open to add code to support other Environments. But I don`t like theme switchers and stuff like that. There must be a better way but I don`t know Gnome.

**Comment by lobau** [comment]
I believe Gnome 42 will have a theme switcher. So far I don't think there is a non-hacky way to know the user's theme
