### ISSUE TITLE
Answer reference does not survive delete/undo

### ISSUE THREAD

**Issue by eater** [parnold-x/nasc#180]
**Describe the bug**
When there's a `lineX` reference to an answer, and you delete it and then undo the deletion, the reference becomes `OBJ`. 

**To Reproduce**
1. Start with a blank sheet.
2. Input `236` on line 1.
3. Input `line1` on line 2. The right column populates correctly with "236".
4. Input `2000` on line 3.
5. Hold the backspace key to delete the contents of lines 2 and 3.
4. Hold Ctrl-z to undo the deletion.
5. Observe that line 2 now contains [OBJ] rather than the reference to line 1.
 

**Expected behavior**
After deleting and undoing, the state should be what it was before the deletion, including references to answers.

**Screenshots**

![2021-09-10_11-42-55](https://user-images.githubusercontent.com/106199/132880608-95c80ff1-aa6c-4b39-93c5-19c3ff832696.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version: 0.8.0

**Comment by parnold-x** [comment]
I changed it, so the information is not lost but the undo stack is getting messed up and I couldn't find a method to edit it. But for now it seems better then before.
