### ISSUE TITLE
Can't build libqalculatenasc

### ISSUE THREAD

**Issue by dogejaker** [parnold-x/nasc#32]
[ 23%] Performing build step for 'libqalculatenasc'
QalculateNasc.cc: In function ‘char* get_function_arguments(int)’:
QalculateNasc.cc:90:85: error: ‘transform’ was not declared in this scope
             transform (str.begin(), str.end(), str.begin(), (int (*) (int) ) tolower);
                                                                                     ^
QalculateNasc.cc: In function ‘char* get_function_arguments_list(int)’:
QalculateNasc.cc:114:85: error: ‘transform’ was not declared in this scope
             transform (str.begin(), str.end(), str.begin(), (int (*) (int) ) tolower);
                                                                                     ^
QalculateNasc.cc: In function ‘void abort()’:
QalculateNasc.cc:199:10: error: declaration of ‘void abort()’ has a different exception specifier
     void abort() {
          ^~~~~
In file included from QalculateNasc.cc:3:0:
QalculateNasc.h:15:6: note: from previous declaration ‘void abort() throw ()’
 void abort();
      ^~~~~
QalculateNasc.cc: In function ‘void abort()’:
QalculateNasc.cc:201:5: warning: ‘noreturn’ function does return
     }
     ^
make[3]: *** [Makefile:16: QalculateNasc.o] Error 1
make[2]: *** [CMakeFiles/libqalculatenasc.dir/build.make:111: ../libqalculatenasc/src/libqalculatenasc-stamp/libqalculatenasc-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/libqalculatenasc.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by dogejaker** [comment]
With highlighting: https://pastebin.com/d95jErn1

**Comment by dogejaker** [comment]
adding:
#include <algorithm>
to libqalculatenasc/QalculateNasc.cc
fixes the transform errors.

Sorry if I'm not being very helpful, I'm new to github and have very little experience with C programming.

**Comment by lf-araujo** [comment]
That also affects me...

**Comment by phinicota** [comment]
It seems to be a naming issue (abort exists in stdlib), made a quick patch for anyone interested:
https://gist.github.com/phinicota/cf1c0cbae068962b4f973b202fc59949

**Comment by parnold-x** [comment]
Great thanks. Will commit this in a second
