### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by PeterNerlich** [parnold-x/nasc#36]
When enabling the dark theme for every window using the elementary os tweak tool, the window border and background colors are overwritten, but the text color does not change, making it really hard to read. It would be awesome if it could somehow display an alternate color palette when using the dark theme globally.

**Comment by parnold-x** [comment]
If you provide the palette and the style-scheme...

**Comment by PeterNerlich** [comment]
The up-to-date stylesheets, including the dark theme, can be found here: https://github.com/elementary/stylesheet/tree/master/gtk-3.0

**Comment by parnold-x** [comment]
I meant this style-scheme [nasc.xml](https://github.com/parnold-x/nasc/blob/nasc/data/styles/nasc.xml)
Not sure if this fits the dark theme.

**Comment by nick87720z** [comment]
Is not it possible, to take colors from current color scheme and adjust it?
For now we have white background and very light text color for result, so text is hard to read.

Yet, some Android apps have option "Color scheme", usually with options Light/Dark.

**Comment by parnold-x** [comment]
the colors are set in the linked nasc.xml style sheet. For dark support there would be the need of a adapted version of that with colors that fit.

**Comment by cristianrm650** [comment]
The color that is causing the problem are set in the ResultView.vala line 59, i just make a Fork with a temporal fix, @nick87720z  you can check it, but you need to compile nasc.

**Comment by zjuhasz** [comment]
Perhaps it would be best to have nasc ignore system theme settings until the dark theme colors are visible. Right now I can't use a dark theme if I want to use nasc.

**Comment by blendmaster** [comment]
A temporary workaround for those also trying to use nasc with a dark theme is to override a light GTK theme just for the process (Ambiance being the default ubuntu theme):

    GTK_THEME=Ambiance nasc

Would be nice if nasc had switchable theme support though.

**Comment by ms-pxxl** [comment]
same issue on kde dark breeze theme

**Comment by Fatih20** [comment]
Yes, please. This is the software with elementaryOS built-in theme. It's unusable.
![image](https://user-images.githubusercontent.com/51940383/83930621-c04d3200-a7c2-11ea-9f19-5af88b575d0e.png)

**Comment by parnold-x** [comment]
Finally Implemented 😃

**Comment by andynu** [comment]
For non elementary OS you you can enable dark mode by tweaking your ~/.config/gtk-3.0/settings.ini

```
[Settings]
gtk-application-prefer-dark-theme=1
```
