### ISSUE TITLE
Fix grammar in AppCenter listing

### ISSUE THREAD

**Issue by MPratley** [parnold-x/nasc#37]
First found here:
https://github.com/elementary/website/issues/1720

File in question
https://github.com/parnold-x/nasc/blob/nasc/data/com.github.parnold-x.nasc.appdata.xml

> Should be:
> `It's an app`
> Instead of:
> `Its an app`
> 
> As "It's" is being used as a contraction of "it is"

**Comment by comradekingu** [comment]
You missed one at the end of that.

**Comment by comradekingu** [comment]
The quality of the whole string overall is poor, it is needlessly long, and there is still another error just like it in there. It also invokes the question of "math/maths" for an audience of people whom will disagree both ways.

I tried fixing it:

> You are not a calculator.
> A clever interpreter takes only what it needs, from all of what you write, to give you only the answers you want. When used in conjunction with other equations, those change along with it.
> 
The name is not intuitive, it might even appear to be scary. Like NaCl is to "salt".
"Calculated normality" or something, would be better.

**Comment by parnold-x** [comment]
Fixed. Not really attached to the string. I just copied it from the mockup. I will not change the name though.

**Comment by bigfatbird** [comment]
Also take care there is a difference between ’ and ' http://practicaltypography.com/apostrophes.html

**Comment by parnold-x** [comment]
So it is --> **it’s** then? We do not use this stuff in my language so no clue :)

**Comment by bigfatbird** [comment]
Yes, correct.

**Comment by parnold-x** [comment]
Thanks. Changed
