### ISSUE TITLE
Bug Trigonometry

### ISSUE THREAD

**Issue by sjodiel** [parnold-x/nasc#52]
Trigonometry functions do not work for angles different from **zero**.

**Comment by parnold-x** [comment]
You have to define the unit of the angle. sin 5° or cos 7rad ...

**Comment by sjodiel** [comment]
174/5000
Hello I was using this way, for example, sin (45) cos (45).
But no results were shown.
Even with using sin (45 º).
Using sin (45 rad) works perfectly.

**Comment by parnold-x** [comment]
sin(45°) works also. So still not sure what the problem is.

**Comment by sjodiel** [comment]
Sorry, I was using error symbol. Instead of ° (degree) I was using º (ordinal)
