### ISSUE TITLE
Right pane background is not filled

### ISSUE THREAD

**Issue by nick87720z** [parnold-x/nasc#54]
After start right pane has contents of what is behind, but it is not transparency, as during window move contents moves too. When result is changed, it is also not cleared.

<a href="http://i.imgur.com/X6jpTeY.png">
  <img src="http://imgur.com/X6jpTeYl.png" />
</a>

gentoo, gtk+-3.22.11, cairo-1.14.8, vala-0.34.8

upd.: in ResultView.vala alpha is set to 0, must be 100
upd2: they are double values

**Comment by parnold-x** [comment]
Hey, maybe it is  something with GTK 3.22. Since the actual version of elementary is targeted it is adapted to 3.18 till the next version.

**Comment by parnold-x** [comment]
Fixed
