### ISSUE TITLE
Conversion between numeral bases

### ISSUE THREAD

**Issue by JonnyCodewalker** [parnold-x/nasc#59]
Add the Ability to convert from Hexadecimal to Binary to Decimal.
Currently NaSC is neither able to represent binary nor able to do math with it.

**Comment by parnold-x** [comment]
Hey, what is the usecase to do math with binary? Also not sure how a convert thing could be good integrated.

**Comment by parnold-x** [comment]
Ah and you can convert already with this.
https://qalculate.github.io/manual/qalculate-definitions-functions.html#qalculate-definitions-functions-2-Number-Bases

**Comment by parnold-x** [comment]
And just looked at the issue tracker there. In the next update of the the calculator lib it will also be possible to convert with syntax like   "2 to hex" "3 to bin"

**Comment by JonnyCodewalker** [comment]
Sorry for the late response. Personally I have to use hexadecimal math in embedded programming from time to time. While beeing basic enough to be done by hand it would be handy to do it via NaSC. Notation for hexadecimal or binary numbers could be F1h or 10100b for hexadecimal/binary. Considering the lib enables conversion this issue can probably be closed?
