### ISSUE TITLE
Sharing via PasteBin gives you "this page has been removed"

### ISSUE THREAD

**Issue by asahnoln** [parnold-x/nasc#60]
When I try sharing the math sheet through PasteBin, the resulting link opens the page which tells me "This page has been removed"
![image](https://user-images.githubusercontent.com/2792908/29347653-eab736ce-826f-11e7-968e-9bd3f6aecf5a.png)
![image](https://user-images.githubusercontent.com/2792908/29347657-f4b25758-826f-11e7-980b-99a52a77caab.png)
After I open this URL: https://pastebin.com/XZw5GUX
![image](https://user-images.githubusercontent.com/2792908/29347669-1782c88a-8270-11e7-9bb8-40ac90b1bdee.png)
It behaves the same with different expiration times, "private" option and different names.

**Comment by parnold-x** [comment]
Thanks. The pastebin api has changed little bit. Fixed
