### ISSUE TITLE
Sharing via PasteBin without expiry time

### ISSUE THREAD

**Issue by asahnoln** [parnold-x/nasc#61]
When I open "Sharing via PasteBin", the dialog gives me no option by default.
It still allows the user to share the sheet without choosing expiry time and it gives back an empty window no link as a result.
![image](https://user-images.githubusercontent.com/2792908/29347722-8a39b26c-8270-11e7-989e-f9a7b4dd7e94.png)
![image](https://user-images.githubusercontent.com/2792908/29347735-a103a548-8270-11e7-8e16-a47b7a18dfb4.png)

**Comment by parnold-x** [comment]
fixed
