### ISSUE TITLE
App keeps running when closing window

### ISSUE THREAD

**Issue by phw** [parnold-x/nasc#74]
Is this intentional or a bug?

**Comment by parnold-x** [comment]
Bug. Did not notice this yet.

**Comment by phw** [comment]
I had experimented with this a bit when dealing with the localization branch. I tried different changes to narrow down the issue, including using `Gtk.Application` instead of `Granite.Application` and `Gtk.ApplicationWindow` instead of `Gtk.Window`. The thing is that the `Application` should usually terminate once its last window gets closed, that's one of the advantages of using `Application`. But it doesn't work here.

Interestingly during testing I once had the app shutdown correctly, but could not reproduce it afterwards. Could this be related to the threading in the calculator?

**Comment by parnold-x** [comment]
Like said. I never observed that. I will most probably switch to Gtk.Application when I rework the app.

**Comment by parnold-x** [comment]
Could not reproduce this. If someone has steps to reproduce. Please open again.
