### ISSUE TITLE
Auto complete parentesis

### ISSUE THREAD

**Issue by Hedronmx** [parnold-x/nasc#75]
Whenver you input a "function" it should automatically input the parentesis.
For example
If I type solve and typed space it should automatically insert parentesis ()

**Comment by parnold-x** [comment]
After playing around with it, I will revert this. This is more a annoyance than helpful.

**Comment by Hedronmx** [comment]
I really like it... why do you find it annoying?

**Comment by parnold-x** [comment]
e.g. when i use trigonometry functions like sin Idont use parentesis and so this inserts them and it interrupt the input flow and I have to close these. Also when there a multiple uses for example days is a function and a unit, so if you calculate 3days + something it inserts not wanted parentesis and so on.

**Comment by Hedronmx** [comment]
Maybe add the option to toggle it the autocompletion?
