### ISSUE TITLE
How to enter e as a number?

### ISSUE THREAD

**Issue by Hedronmx** [parnold-x/nasc#77]
I tried using euler but the value of that variable is .5772 etc. Using e on its own returns nothing.

I want to calculate ln e, but it returns nothing. I also tried log e. It should return 1

**Comment by parnold-x** [comment]
Hi, it is e. See Base of Natural Logarithms (e) in the Help.
The problem here is that it doesn't detect that is should calculate something if used isolated if you add something or so it works just fine. I will rework some things this winter including the calculation part...
