### ISSUE TITLE
Can't copy single calculation on right.

### ISSUE THREAD

**Issue by gelldur** [parnold-x/nasc#79]
Linux Manjaro - probably current app (no version is visible :( )
Example on left:  `(1 -0.02839446 /0.0284405) * 100 `
On right I see: `0.16188182`

When I select on right side `0.16188182` and click copy it doesn't work (no copy)

Ok it is working when pure numbers are in input for such input it doesn't work:

```
#Hello World

(1 -0.02839446 /0.0284405) * 100 
```

**Comment by parnold-x** [comment]
I disabled the menu and it copies now directly after right click. What's a bit bad is that no gui response is given now. Maybe in the future.
