### ISSUE TITLE
Support HiDPI Screens

### ISSUE THREAD

**Issue by jarradh** [parnold-x/nasc#80]
It seems HiDPI support doesn't work well in NaSC.

Running normally window decorator is fine but text is small, 
running `GDK_SCALE=2 nasc` makes text normal but makes window decoration very large.

Other Gtk applications are scaled fine.

**Comment by parnold-x** [comment]
Looks ok here.
![bildschirmfoto von 2017-12-24 15-40-20](https://user-images.githubusercontent.com/3041711/34327294-dffce820-e8c0-11e7-8824-e841a034e948.png)

**Comment by jarradh** [comment]
That doesn't look okay(and is what I'm seeing if I use GDK_SCALE look at your title bar in comparison to the background window, it's gargantuan. Same icons, double the size.

**Comment by parnold-x** [comment]
I not sure I get it. The icons should be double the size if you scale them to 2. The background window is not scaled so sure there is a difference. Can you post a screenshot without any scale option or something because if you have HiDPI it should make it right out of the box.

**Comment by jarradh** [comment]
So this is using KDE, other GTK apps behave fine and use correct decorations, however Nasc is incredibly small to read (not obeying scaling for some reason on its own)

![screenshot_20171228_052323](https://user-images.githubusercontent.com/2714786/34393745-8a13a960-eb4c-11e7-8366-2522652ccdea.jpg)

**Comment by parnold-x** [comment]
Mhh, ok. Maybe it is a issue with GTK support in KDE. Anyway I don't know what I could do to fix this. I also have no HiDPI and target is still elementary. But I am open for PRs.

**Comment by myfreeweb** [comment]
HiDPI is completely fine under Weston :)

If that KDE is running with X, try setting `Xft.dpi: 144` (or whatever your value is) in `~/.Xresources` (apply with `xrdb -merge ~/.Xresources`).

**Comment by parnold-x** [comment]
Close this because its a problem with some window manager settings
