### ISSUE TITLE
install libqalculatenasc.so to a private lib directory

### ISSUE THREAD

**Issue by decathorpe** [parnold-x/nasc#81]
Currently, the private and unversioned libqalculatenasc.so shared library is installed directly to LIBDIR, where ldconfig would pick it up as a public shared library.

Please install it into a private LIBDIR subdirectory (for example, LIBDIR/qalculatenasc/libqalculatenasc.so).

**Comment by decathorpe** [comment]
Whatever you changed with version 0.4.7, `libqalculatenasc.so` isn't installed at all anymore, and it breaks the application here due to the missing shared library.

**Comment by decathorpe** [comment]
Maybe a simpler approach: If you don't expect any other applications to use `libqalculatenasc.so`, you could also just build it as a normal object, link it into the main binary, and drop the shared library altogether.

**Comment by decathorpe** [comment]
I'll send you a pull request if I can find the time.

**Comment by decathorpe** [comment]
Well, this was simpler than I thought.

**Comment by parnold-x** [comment]
Thanks!
