### ISSUE TITLE
could you make a flatpak for nasc?

### ISSUE THREAD

**Issue by altntowin** [parnold-x/nasc#82]
Hi, I really appreciate your work , is a good application
but i don't use elementary OS
could you make a flatpak for nasc?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by parnold-x** [comment]
https://github.com/phw/nasc-flatpak

**Comment by altntowin** [comment]
Thanks

**Comment by scx** [comment]
New attempt to create a flatpak package:
https://github.com/parnold-x/nasc/issues/105
https://github.com/flathub/flathub/pull/867

See also:
https://github.com/scx/nasc-flatpak
