### ISSUE TITLE
Add ability to convert Decimal to Binary.

### ISSUE THREAD

**Issue by SubhadeepJasu** [parnold-x/nasc#83]
I was doing a sort of data problem and I needed a way to convert decimal to binary. Just the reverse of `decimal = bin(<binary>)`.

**Comment by eugeneia** [comment]
What if binary/hex/octal were treated as units, so you could:
```
0b01 * 2              0b10
ans to decimal        2
```

etc?

**Comment by parnold-x** [comment]
This works now see #116
