### ISSUE TITLE
Inch abbreviation

### ISSUE THREAD

**Issue by laurence-wilson** [parnold-x/nasc#84]
Can we do something about the following? Took me a few seconds to realise I had to type inch longhand. Was the first conversion I attempted to use in the app! The problem applies also to feet and '.

![screenshot from 2018-02-16 22-27-31](https://user-images.githubusercontent.com/36552948/36332267-731ef59e-1369-11e8-9d2b-9a6e04070d68.png)

**Comment by parnold-x** [comment]
You can also just use in and ft
I thought about this a little and i will not add this because i want keep the unit stuff consistent to libqalculate. Maybe suggest it there https://github.com/Qalculate/libqalculate
