### ISSUE TITLE
Help not correctly escaped

### ISSUE THREAD

**Issue by jtojnar** [parnold-x/nasc#92]
When I select “vector limits” from the Help menu, the following warning is logged to console:

(nasc:21108): Gtk-WARNING **: 15:24:15.412: Failed to set text '<small>vector: a vector
lower limit: an integer >= -2147483648 and <= 2147483647
upper limit: an integer >= -2147483648 and <= 2147483647</small>' from markup due to error parsing markup: Error on line 2 char 46: '=' is not a valid character following a '<' character; it may not begin an element name

**Comment by parnold-x** [comment]
Thanks. Fixed
