### ISSUE TITLE
Release on Juno

### ISSUE THREAD

**Issue by peteruithoven** [parnold-x/nasc#96]
Would be awesome if this app was also released on elementary Juno.
See: [Developer Tips: Updating Your Apps for Juno](https://medium.com/elementaryos/developer-tips-updating-your-apps-for-juno-453c07a5b3a7)

**Comment by danrabbit** [comment]
Our [second Juno Developer Preview](https://medium.com/elementaryos/developer-preview-juno-beta-2-is-out-418f5037e9bb) is out and Juno's big debut is just around the corner! We'd love to see your app in AppCenter on release day.

Check out this [Developer Tips](https://medium.com/elementaryos/developer-tips-updating-your-apps-for-juno-453c07a5b3a7) article to learn how to publish your app for elementary OS 5.

If you need help updating your app for Juno, we’re always standing by in [Gitter](https://gitter.im/elementary/houston) and the [Community Slack](https://join.slack.com/t/elementarycommunity/shared_invite/enQtMzU1NDU4OTE1MjY2LWUyOTBkZGNkZGM4MDgzZjE2ZjRiZDgwMDQ1ZTA0MzcxYjI0MDUyNGRlNDI5ZWViNDkwMzMwYzczMDY2ZjA0MTc) to help wherever we can.

**Comment by Hedronmx** [comment]
Please add support for Juno

**Comment by parnold-x** [comment]
Is up for review

**Comment by eljefuri** [comment]
@parnold-x I just want to say thanks *so much* for supporting Elementary with this fantastic, almost indispensable application. I have been really suffering without NaSC in my Juno toolkit!
