### ISSUE TITLE
Crash on start with missing lib

### ISSUE THREAD

**Issue by danrabbit** [parnold-x/nasc#97]
It looks like in your debian packaging you didn't add libqalculate as a runtime dependency. This makes NaSC crash with:

```
com.github.parnold-x.nasc: error while loading shared libraries: libqalculatenasc.so: cannot open shared object file: No such file or directory
```

**Comment by parnold-x** [comment]
ok, strange it worked before. Can you tell me where to add it?

**Comment by danrabbit** [comment]
It would be under "Depends" here: https://github.com/parnold-x/nasc/blob/master/debian/control#L20

**Comment by danrabbit** [comment]
I'm still seeing this same issue with the latest package. Is there a library that nasc itself builds that needs to be installed? I noticed that it says libqalculate**nasc**.so

**Comment by cassidyjames** [comment]
@parnold-x any update? It looks like the 0.5.1 package still has this issue: http://packages.elementary.io/testing/pool/main/c/com.github.parnold-x.nasc/com.github.parnold-x.nasc0.5.1-0e4ac8.deb

**Comment by scx** [comment]
Proposed patches:
https://github.com/parnold-x/nasc/pull/108
